baseURL: https://example.com
title: Blonde
author: wamo
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
theme: Blonde
enableRobotsTXT: yes
params:
  archive_dropdown: 'false'
  base_color: bg-gray-800
  darkmode: light
  description: Blonde theme for Hugo.
  paginator_pages: '5'
  post:
    description: '130'
    noimage: yes
    thumbnail: yes
    thumbnail_height: h-44
    thumbnail_width: w-auto
  tagsLimit: 20
  widgets:
    display: yes
    widgets:
      - search
      - archive
      - category
      - tags
      - recent
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 3
taxonomies:
  archive: archives
  category: categories
  tag: tags
privacy:
  instagram:
    disabled: no
    simple: yes
  twitter:
    disabled: no
    enableDNT: yes
    simple: yes
  vimeo:
    disabled: no
    simple: yes
  youtube:
    disabled: no
    privacyEnhanced: yes
services:
  instagram:
    disableInlineCSS: yes
  twitter:
    disableInlineCSS: yes
build:
  writeStats: yes
